# Generated by Django 5.2.14 on 2026-05-08 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("taxonomy", "0002_workgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="taxonomy.workgroup",
            ),
        ),
    ]
