# Generated by Django 5.2.14 on 2026-05-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_sitesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Administrator"),
                    ("auditor", "Auditor"),
                    ("group_leader", "Group Leader"),
                ],
                db_index=True,
                default="user",
                max_length=16,
            ),
        ),
    ]
