# Generated by Django 5.2.14 on 2026-05-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_group_leader_role"),
        ("taxonomy", "0002_workgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="managed_groups",
            field=models.ManyToManyField(
                blank=True, related_name="division_heads", to="taxonomy.workgroup"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Administrator"),
                    ("auditor", "Auditor"),
                    ("group_leader", "Group Leader"),
                    ("division_head", "Division Head"),
                ],
                db_index=True,
                default="user",
                max_length=16,
            ),
        ),
    ]
