# Generated by Django 5.2.14 on 2026-05-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_functional_lead_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("functional_lead", "Functional Lead"),
                    ("group_leader", "Group Leader"),
                    ("division_head", "Division Head"),
                    ("auditor", "Auditor"),
                    ("admin", "Administrator"),
                ],
                db_index=True,
                default="user",
                max_length=16,
            ),
        ),
    ]
