# Generated by Django 5.2.14 on 2026-06-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_institution_user_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="collaboration_code",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="institution",
            name="collaboration_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="institution",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="collaboration_flag",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="collaboration_international",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="collaboration_member_number",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="collaboration_position",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="collaboration_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="collaboration_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="fnal_username",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="github_username",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="inspire_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="is_collaboration_member",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="minority_serving",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_phone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="office_phone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="orcid",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="other_phone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="roster_comments",
            field=models.TextField(blank=True),
        ),
    ]
