# Generated by Django 5.2.14 on 2026-06-01 18:04

from django.db import migrations, models


def separate_roster_contact_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_collaboration_member=False).update(roster_merge_completed=True)
    for user in User.objects.filter(is_collaboration_member=True):
        if user.email and not user.contact_email:
            user.contact_email = user.email
            user.email = ""
            user.save(update_fields=["contact_email", "email"])


def reverse_separate_roster_contact_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(is_collaboration_member=True, email="").exclude(contact_email=""):
        user.email = user.contact_email
        user.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_institution_collaboration_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Contact Email"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="roster_merge_completed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Login Email"
            ),
        ),
        migrations.RunPython(
            separate_roster_contact_emails,
            reverse_separate_roster_contact_emails,
        ),
    ]
