# Generated by Django 5.2.14 on 2026-06-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_contact_email_user_roster_merge_completed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="employee_id",
        ),
    ]
