# Generated by Django 5.2.14 on 2026-06-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_user_employee_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=160, unique=True)),
                (
                    "normalized_alias",
                    models.CharField(
                        db_index=True, editable=False, max_length=160, unique=True
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="accounts.institution",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Institution aliases",
                "ordering": ["alias"],
            },
        ),
    ]
