# Generated by Django 5.2.14 on 2026-06-03 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_institutionalias"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name_alias", models.CharField(blank=True, max_length=128)),
                ("last_name_alias", models.CharField(blank=True, max_length=128)),
                ("full_name_alias", models.CharField(blank=True, max_length=255)),
                (
                    "normalized_alias",
                    models.CharField(
                        db_index=True, editable=False, max_length=255, unique=True
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_aliases",
                        to="accounts.institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User aliases",
                "ordering": ["last_name_alias", "first_name_alias", "full_name_alias"],
            },
        ),
    ]
