# Generated by Django 5.2.14 on 2026-06-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_collaboration_position_choices"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
