apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mu2e-talks-simple.labels" . | nindent 4 }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.django.settingsModule | quote }}
  DJANGO_ALLOWED_HOSTS: {{ if .Values.route.hostname }}{{ printf "%s,%s" .Values.route.hostname .Values.django.allowedHosts | quote }}{{ else }}{{ .Values.django.allowedHosts | quote }}{{ end }}
  {{- if .Values.route.hostname }}
  CSRF_TRUSTED_ORIGINS: {{ printf "https://%s" .Values.route.hostname | quote }}
  {{- end }}
  ACCOUNT_EMAIL_VERIFICATION: {{ .Values.django.emailVerification | quote }}
  MU2E_DISABLE_LOCAL_SIGNUP: {{ .Values.django.disableLocalSignup | quote }}
  LOCAL_LOGIN_ENABLED: {{ .Values.django.localLoginEnabled | quote }}
  MU2E_INITIAL_ADMIN_USERNAME: {{ .Values.django.initialAdminUsername | quote }}
  MU2E_INITIAL_ADMIN_EMAIL: {{ .Values.django.initialAdminEmail | quote }}
  DATABASE_URL: {{ .Values.database.url | quote }}
  GUNICORN_WORKERS: {{ .Values.gunicorn.workers | quote }}
  GUNICORN_LOG_LEVEL: {{ .Values.gunicorn.logLevel | quote }}
  EMAIL_HOST: {{ .Values.email.host | quote }}
  EMAIL_PORT: {{ .Values.email.port | quote }}
  EMAIL_HOST_USER: {{ .Values.email.user | quote }}
  DEFAULT_FROM_EMAIL: {{ .Values.email.defaultFrom | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.google.clientId | quote }}
  OIDC_PROVIDER_URL: {{ .Values.oidc.providerUrl | quote }}
  OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
