apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-media
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mu2e-talks-simple.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.media.size }}
