# Generated by Django 5.2.14 on 2026-06-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="talk",
            name="parallel",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Parallel"
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="plenary",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Plenary"
            ),
        ),
    ]
