# Generated by Django 5.2.14 on 2026-06-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talks", "0002_talk_parallel_talk_plenary"),
    ]

    operations = [
        migrations.AddField(
            model_name="talk",
            name="type",
            field=models.CharField(
                choices=[
                    ("overview", "Overview"),
                    ("conference", "Conference"),
                    ("seminar", "Seminar"),
                    ("colloquium", "Colloquium"),
                    ("job_talk", "Job Talk"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=16,
            ),
        ),
    ]
