# Generated by Django 5.2.14 on 2026-06-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talks", "0003_talk_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="inspire_id",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                unique=True,
                verbose_name="INSPIRE ID",
            ),
        ),
    ]
