# Generated by Django 5.2.14 on 2026-06-03 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_user_employee_id"),
        ("talks", "0005_seed_inspire_conferences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="talk",
            name="arxiv_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="talk",
            name="committee_approved_raw",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Committee Approval"
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="docdb_certificate_number",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="DocDB Certificate Number"
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="docdb_password_number",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="DocDB Password Number"
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="talk",
            name="duration_raw",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="talk",
            name="mu2e_program",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="Mu2e/Mu2e-II"
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="presentation_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="talk",
            name="proceedings_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="talk",
            name="source_row",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="talk",
            name="source_sheet",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="talk",
            name="source_spreadsheet",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="talk",
            name="speaker_first_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="talk",
            name="speaker_home_institution_raw",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="talk",
            name="speaker_institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="talk_speaker_records",
                to="accounts.institution",
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="speaker_last_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="talk",
            name="spreadsheet_import_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="talk",
            name="spreadsheet_type_raw",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Spreadsheet Type"
            ),
        ),
        migrations.AddIndex(
            model_name="talk",
            index=models.Index(
                fields=["presentation_date"], name="talks_talk_present_aad2a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="talk",
            index=models.Index(
                fields=["source_spreadsheet", "source_sheet", "source_row"],
                name="talks_talk_source__5f5604_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="talk",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source_row__isnull", False),
                    ("source_sheet__gt", ""),
                    ("source_spreadsheet__gt", ""),
                ),
                fields=("source_spreadsheet", "source_sheet", "source_row"),
                name="talks_talk_unique_spreadsheet_row",
            ),
        ),
    ]
