#!/usr/bin/env bash
# Generate a Helm chart from a Docker Compose file using kompose.
#
# Usage:
#   ./scripts/generate-helm-chart.sh [OPTIONS]
#
# Options:
#   -f FILE       Compose file to convert (default: compose-simple.yaml)
#   -o DIR        Output directory for the chart (default: helm/<chart-name>)
#   -n NAMESPACE  Kubernetes namespace to embed in resources (default: mu2e-talks)
#   -r REPLICAS   Number of replicas for deployments (default: 1)
#   --pvc-size    PVC storage request size (default: 1Gi)
#   -h            Show this help message

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# ── Defaults ──────────────────────────────────────────────────────────────────
COMPOSE_FILE="${REPO_ROOT}/compose-simple.yaml"
OUTPUT_DIR=""
NAMESPACE="mu2e-talks"
REPLICAS=1
PVC_SIZE="1Gi"

# ── Argument parsing ──────────────────────────────────────────────────────────
usage() {
    sed -n '/^# Usage:/,/^[^#]/{ /^#/{ s/^# \{0,2\}//; p } }' "$0"
    exit 0
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -f) COMPOSE_FILE="$2"; shift 2 ;;
        -o) OUTPUT_DIR="$2";   shift 2 ;;
        -n) NAMESPACE="$2";    shift 2 ;;
        -r) REPLICAS="$2";     shift 2 ;;
        --pvc-size) PVC_SIZE="$2"; shift 2 ;;
        -h|--help) usage ;;
        *) echo "Unknown option: $1" >&2; usage ;;
    esac
done

# ── Validate inputs ───────────────────────────────────────────────────────────
if ! command -v kompose &>/dev/null; then
    echo "ERROR: kompose is not installed or not on PATH." >&2
    echo "       Install it with:  brew install kompose" >&2
    echo "       Or see: https://kompose.io/installation/" >&2
    exit 1
fi

if [[ ! -f "${COMPOSE_FILE}" ]]; then
    echo "ERROR: Compose file not found: ${COMPOSE_FILE}" >&2
    exit 1
fi

# Derive chart name from the compose filename (strip path and extension)
COMPOSE_BASENAME="$(basename "${COMPOSE_FILE}")"
CHART_NAME="${COMPOSE_BASENAME%.yaml}"
CHART_NAME="${CHART_NAME%.yml}"
CHART_NAME="${CHART_NAME#compose-}"      # strip leading "compose-"
CHART_NAME="${CHART_NAME:-mu2e-talks}"

# Default output dir derived from chart name
if [[ -z "${OUTPUT_DIR}" ]]; then
    OUTPUT_DIR="${REPO_ROOT}/helm/${CHART_NAME}"
fi

# ── Pre-flight summary ────────────────────────────────────────────────────────
echo "kompose  : $(kompose version)"
echo "Compose  : ${COMPOSE_FILE}"
echo "Chart    : ${CHART_NAME}"
echo "Output   : ${OUTPUT_DIR}"
echo "Namespace: ${NAMESPACE}"
echo "Replicas : ${REPLICAS}"
echo "PVC size : ${PVC_SIZE}"
echo ""

# Remove stale output so kompose always writes a clean chart
if [[ -d "${OUTPUT_DIR}" ]]; then
    echo "Removing existing output directory: ${OUTPUT_DIR}"
    rm -rf "${OUTPUT_DIR}"
fi
mkdir -p "$(dirname "${OUTPUT_DIR}")"

# ── Run kompose ───────────────────────────────────────────────────────────────
echo "Running kompose convert ..."
kompose convert \
    --file        "${COMPOSE_FILE}" \
    --chart \
    --out         "${OUTPUT_DIR}" \
    --namespace   "${NAMESPACE}" \
    --replicas    "${REPLICAS}" \
    --pvc-request-size "${PVC_SIZE}" \
    --volumes     persistentVolumeClaim

echo ""
echo "Chart written to: ${OUTPUT_DIR}"
echo ""

# ── Post-process: fix Chart.yaml (kompose uses the abs path as the chart name) ─
CHART_YAML="${OUTPUT_DIR}/Chart.yaml"
if [[ -f "${CHART_YAML}" ]]; then
    # Replace every field that kompose set to the absolute output path
    sed -i.bak \
        -e "s|^name:.*|name: ${CHART_NAME}|" \
        -e "s|^description:.*|description: Mu2eTalks — generated by kompose from ${COMPOSE_BASENAME}|" \
        -e "/^keywords:/{ n; s|.*- .*/${CHART_NAME}.*|  - mu2e-talks|; }" \
        "${CHART_YAML}"
    rm -f "${CHART_YAML}.bak"

    if ! grep -q "^appVersion:" "${CHART_YAML}"; then
        echo "appVersion: \"latest\"" >> "${CHART_YAML}"
    fi
    echo "Patched: ${CHART_YAML}"
fi

# ── Optional helm lint ────────────────────────────────────────────────────────
if command -v helm &>/dev/null; then
    echo ""
    echo "Running helm lint ..."
    helm lint "${OUTPUT_DIR}" && echo "helm lint: OK"
else
    echo "NOTE: helm is not installed — skipping lint."
    echo "      Install with:  brew install helm"
fi

echo ""
echo "Done.  To install the chart:"
echo "  helm install ${CHART_NAME} ${OUTPUT_DIR} --namespace ${NAMESPACE} --create-namespace"
