# Generated by Django 5.2.14 on 2026-05-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIPromptConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        default="You are an analyst writing structured effort-reporting summaries for a scientific computing department. Your summaries are factual, professional, and well-organised. Use Markdown headings and bullet points. Do not invent information beyond what is provided."
                    ),
                ),
                (
                    "user_template",
                    models.TextField(
                        default="Below is a set of effort talks from the Mu2eTalks system.\nPlease write a concise narrative summary that includes:\n\n1. **Overview** – date range covered, total talks, and authors involved.\n2. **Key Themes** – the main types of work and projects represented.\n3. **Notable Work** – standout contributions, especially any marked CRITICAL or HIGHLIGHT.\n4. **Summary Table** – a compact Markdown table with columns: Author | Project | Category | Period | Title.\n\n---\n{talks}\n"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Prompt Configuration",
            },
        ),
    ]
